pipeline {
    agent any

    environment {
        JAVA_HOME = 'C:\\Program Files\\Eclipse Adoptium\\jdk-21.0.8.9-hotspot'
        PATH = "${JAVA_HOME}\\bin;${env.PATH}"
        GRADLE_USER_HOME = 'C:\\Users\\Lorenzo\\.gradle'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('esameProgValid') {
                    bat 'gradlew.bat clean build'
                }
            }
        }

        stage('Test') {
            steps {
                dir('esameProgValid') {
                    bat 'gradlew.bat test'
                }
            }
        }

        stage('Archive Artifact') {
            steps {
                archiveArtifacts artifacts: 'esameProgValid/build/libs/*.jar'
            }
        }
    }
}